export const GET_COURSES = "GET_COURSES";
export const GET_TITLE_COURSES = "GET_TITLE_COURSES";
export const GET_COURSES_TITLE = "GET_COURSES_TITLE";
// user
export const GET_USER = "GET_USER";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const REGISTER_USER = "REGISTER_USER";
